version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging into ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - IMAGE_TAG=$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      # Build the docker images
      - echo Build started on `date`
      - echo Building docker images...
      - docker build -t $REPOSITORY_URI:spig-front-latest ./front-end
      - docker tag $REPOSITORY_URI:spig-front-latest $REPOSITORY_URI:spig-front-$IMAGE_TAG 
      - docker build -t $REPOSITORY_URI:spig-back-latest ./back-end
      - docker tag $REPOSITORY_URI:spig-back-latest $REPOSITORY_URI:spig-back-$IMAGE_TAG 
  post_build:
    commands:
      # Push images to ECR
      - echo Build completed on `date`
      - echo Pushing docker images to ECR...
      - docker push $REPOSITORY_URI:spig-front-latest
      - docker push $REPOSITORY_URI:spig-front-$IMAGE_TAG 
      - docker push $REPOSITORY_URI:spig-back-latest
      - docker push $REPOSITORY_URI:spig-back-$IMAGE_TAG 