version: '3.8'

volumes:
    db-data:
        external: false

services:
    db:
        env_file:
            - ./back-end/.env
        image: postgres
        volumes:
            - db-data:/usr/local/pgsql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
    
    backend:
        build: ./back-end/
        #volumes: 
        #    - ./back-end/:/usr/src/app
        ports:
            - '3000:3000'
        depends_on: 
            db:
                condition: service_healthy
    
    # Production
    #frontend:
    #    build: ./front-end/
    #    ports:
    #        - '4000:80'
    
    # Development
    frontend:
        build:
            context: ./front-end/
            dockerfile: Dockerfile.dev
        volumes:
            - ./front-end/:/usr/src/app
            - /usr/src/app/node_modules
        ports: 
            - '1234:1234'